// Jenkinsfile
String gcpCredentialsId = 'gcp-demblock-service-account'
String sqlCredentialsId = 'demblock-sql-credentials'

try {
  stage('checkout') {
    node {
      cleanWs()
      checkout scm
    }
  }

  // Run terraform init
  stage('init') {
    node {
      withCredentials(
          file([credentialsId: gcpCredentialsId, variable: 'GC_KEY']),
          usernamePassword(credentialsId: sqlCredentialsId, usernameVariable: 'TF_VAR_SQL_USER', passwordVariable: 'TF_VAR_SQL_PASSWORD')
        ) {
        ansiColor('xterm') {
            sh './auth.sh'
            sh 'terraform init -var "region=$TF_VAR_SQL_USER" -var'
        }
      }
    }
  }

  // Run terraform plan
  stage('plan') {
    node {
      withCredentials(
          file([credentialsId: gcpCredentialsId, variable: 'GC_KEY']),
          usernamePassword(credentialsId: sqlCredentialsId, usernameVariable: 'TF_VAR_SQL_USER', passwordVariable: 'TF_VAR_SQL_PASSWORD')
        ) {
        ansiColor('xterm') {
            sh './auth.sh'
            sh 'terraform plan'
        }
      }
    }
  }

  if (env.BRANCH_NAME == 'master') {
    // Run terraform apply
    stage('apply') {
      node {
        withCredentials(
          file([credentialsId: gcpCredentialsId, variable: 'GC_KEY']),
          usernamePassword(credentialsId: sqlCredentialsId, usernameVariable: 'TF_VAR_SQL_USER', passwordVariable: 'TF_VAR_SQL_PASSWORD')
         ) {
          ansiColor('xterm') {
            sh './auth.sh'
            sh 'terraform apply -auto-approve'
          }
        }
      }
    }

    // Run terraform show
    stage('show') {
      node {
        withCredentials(
          file([credentialsId: gcpCredentialsId, variable: 'GC_KEY']),
          usernamePassword(credentialsId: sqlCredentialsId, usernameVariable: 'TF_VAR_SQL_USER', passwordVariable: 'TF_VAR_SQL_PASSWORD')
         ) {
          ansiColor('xterm') {
            sh './auth.sh'
            sh 'terraform show'
          }
        }
      }
    }
  }
  currentBuild.result = 'SUCCESS'
}
catch (org.jenkinsci.plugins.workflow.steps.FlowInterruptedException flowError) {
  currentBuild.result = 'ABORTED'
}
catch (err) {
  currentBuild.result = 'FAILURE'
  throw err
}
finally {
  if (currentBuild.result == 'SUCCESS') {
    currentBuild.result = 'SUCCESS'
  }
}