name: 'TF - Deploy Infrastructure'
on:
  watch:
    types: [started]
jobs:
  terraform:
    name: 'Infra - Deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Google Cloud Auth'
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
        
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: './infrastructure'
        env:
          TF_VAR_SQL_USER: ${{ secrets.SQL_USER }}
          TF_VAR_SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './infrastructure'
        env:
          TF_VAR_SQL_USER: ${{ secrets.SQL_USER }}
          TF_VAR_SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}

      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: './infrastructure'
        env:
          TF_VAR_SQL_USER: ${{ secrets.SQL_USER }}
          TF_VAR_SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}

      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: './infrastructure'
        env:
          TF_VAR_SQL_USER: ${{ secrets.SQL_USER }}
          TF_VAR_SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}

      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: './infrastructure'
        env:
          TF_VAR_SQL_USER: ${{ secrets.SQL_USER }}
          TF_VAR_SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
