name: 'TF'
on: push
jobs:
  terraform:
    name: 'Infra - Destroy'
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '#destroy')"
    steps:
      - uses: actions/checkout@master
      - name: 'Google Cloud Auth'
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GOOGLE_SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_SA_KEY }}
          export_default_credentials: true

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './infrastructure'
        env:
          TF_VAR_SQL_USER: ${{ secrets.DB_USERNAME }}
          TF_VAR_SQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACTIONS_TOKEN }}

      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: './infrastructure'
        env:
          TF_VAR_SQL_USER: ${{ secrets.DB_USERNAME }}
          TF_VAR_SQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACTIONS_TOKEN }}

      - name: 'Terraform Destroy'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'destroy'
          tf_actions_working_dir: './infrastructure'
        env:
          TF_VAR_SQL_USER: ${{ secrets.DB_USERNAME }}
          TF_VAR_SQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACTIONS_TOKEN }}
