name: 'TF'
on:
  - pull_request

env:
  TF_VAR_SQL_USER: ${{ secrets.DB_USERNAME }}
  TF_VAR_SQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
  GITHUB_TOKEN: ${{ secrets.GIT_ACTIONS_TOKEN }}
  TF_VAR_GKE_CLUSTER: eu-demblock-cluster
  TF_VAR_GKE_ZONE: europe-north1-a
  TF_VAR_DB_INSTANCE: eu-demblock-db
  TF_VAR_DB_LOCATION: europe-north1

jobs:
  terraform:
    name: 'Infra - Validate PR'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Google Cloud Auth'
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GOOGLE_SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_SA_KEY }}
          export_default_credentials: true

      - name: 'Infra - Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: './infrastructure'

      - name: 'Infra - Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './infrastructure'

      - name: 'Infra - Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: './infrastructure'

      - name: 'Infra - Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: './infrastructure'
