name: 'Infrastructure'
on:
  # =================================================================
  # when user submits a PR to make sure only valid code is commited.
  - pull_request

# =================================================================
# Initialize environment.
# Referenced secrets should be configured before running this step.
# =================================================================
env:
  # Project specific
  TF_VAR_GKE_CLUSTER : eu-demblock-cluster
  TF_VAR_GKE_ZONE    : europe-west1-b
  TF_VAR_DB_INSTANCE : eu-db-demblock
  TF_VAR_DB_LOCATION : europe-west1

  # User specific
  TF_VAR_SQL_USER    : ${{ secrets.DB_USERNAME }}
  TF_VAR_SQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
  GITHUB_TOKEN       : ${{ secrets.GIT_ACTIONS_TOKEN }}

jobs:
  # =================================================================
  # Validate infrastructure.
  # =================================================================
  terraform:
    name: 'Validate PR'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Infra - Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: './infrastructure'

      - name: 'Infra - Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './infrastructure'

      - name: 'Infra - Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: './infrastructure'

      - name: 'Infra - Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: './infrastructure'
