name: 'Secret Management'
on:
  # =================================================================
  # When a new tag is pushed, we update all the secrets in 
  # all dependent repositories
  push:
    tags:
    - '*'

jobs:
  # =================================================================
  # Update infrastructure secrets.
  # =================================================================
  secrets:
    name: 'Update shared configs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update marked repo secrets
        uses: google/secrets-sync-action@v1.1.3
        with: 
          # we update the following secrets
          SECRETS: |
            ^DB_HOST$
            ^SMTP_HOST$
            ^SMTP_PORT$
            ^GCP_PROJECT$
            ^GKE_CLUSTER$
            ^GKE_ZONE$
            ^GIT_AUTH_TOKEN$
            ^GOOGLE_SA_EMAIL$
            ^GOOGLE_SA_KEY$
            ^DOCKER_PASSWORD$
          # in following repositories
          REPOSITORIES: |
            ^NedimRenesalis/demblock$
            ^NedimRenesalis/demblock-tge$
            ^NedimRenesalis/token-demblock-tge$
          GITHUB_TOKEN: ${{ secrets.GIT_ACTIONS_TOKEN }}
        env:
          GCP_PROJECT    : demblock-prod
          GKE_CLUSTER    : eu-demblock-cluster
          GKE_ZONE       : europe-north1-a
          DB_HOST        : ${{ secrets.DB_HOST }}
          SMTP_HOST      : ${{ secrets.SMTP_HOST }}
          SMTP_PORT      : ${{ secrets.SMTP_PORT }}
          GIT_AUTH_TOKEN : ${{ secrets.GIT_ACTIONS_TOKEN }}
          GOOGLE_SA_EMAIL: ${{ secrets.GOOGLE_SA_EMAIL }}
          GOOGLE_SA_KEY  : ${{ secrets.GOOGLE_SA_KEY }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
