name: 'Continuos Deployment'
on:
  push:
    tags:
    - '*'
jobs:
  terraform:
    name: 'Shared secrets'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update
        uses: google/secrets-sync-action@v1.1.3
        with: 
          SECRETS: |
            ^DB_USERNAME$
            ^DB_PASSWORD$
            ^DB_HOST$
            ^SMTP_HOST$
            ^SMTP_PORT$
            ^SMTP_USERNAME$
            ^SMTP_PASSWORD$
            ^GKE_CLUSTER$
            ^GKE_ZONE$
            ^GIT_AUTH_TOKEN$
            ^GOOGLE_SA_EMAIL$
            ^GOOGLE_SA_KEY$
            ^DOCKER_PASSWORD$
          REPOSITORIES: |
            ^NedimRenesalis/demblock$
            ^NedimRenesalis/demblock-tge$
            ^NedimRenesalis/token-demblock-tge$
          GITHUB_TOKEN: ${{ secrets.GIT_ACTIONS_TOKEN }}
        env:
          GKE_CLUSTER: eu-demblock-cluster
          GKE_ZONE: europe-north1-a
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          GIT_AUTH_TOKEN: ${{ secrets.GIT_ACTIONS_TOKEN }}
          GOOGLE_SA_EMAIL: ${{ secrets.GOOGLE_SA_EMAIL }}
          GOOGLE_SA_KEY: ${{ secrets.GOOGLE_SA_KEY }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    